mesa-pvr: Mark it machine arch package
It conflicts with upstream mesa builds otherwise from core layer, in multi
machine build e.g. when builds for qemuriscv64 are done in same project
then packaging for mesa-pvr and mesa would conflict since both provide
same packages and duplicate file staging errors happen e.g.

ERROR: mesa-pvr-2_22.1.3-r0 do_create_spdx: Recipe mesa-pvr is trying to install files into a shared area when those files already exist. The files and the manifests listing them are:
  /mnt/b/yoe/master/build/tmp/deploy/spdx/riscv64/packages/libgl-mesa-dev.spdx.json
    (matched in manifest-riscv64-mesa.create_spdx)

Signed-off-by: Khem Raj <raj.khem@gmail.com>