u-boot: fix k1 SRC_URI
Remove the repository URL from the SRC_URI line for K1 boards, so that
we use the same mirror as oe-core for u-boot. This allows a patch[1]
from oe-core to be applied for Python 3 compatibility in pylibfdt.
Otherwise, we run into errors at the do_compile step:

|scripts/dtc/pylibfdt/libfdt_wrap.c:6733:17: error: assignment to ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
| 6733 |       resultobj = PyString_FromString(
|      |                 ^
|scripts/dtc/pylibfdt/libfdt_wrap.c:6796:17: error: assignment to ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
| 6796 |       resultobj = PyString_FromString(
|      |                 ^
|scripts/dtc/pylibfdt/libfdt_wrap.c:6861:17: error: assignment to ‘PyObject *’ {aka ‘struct _object *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
| 6861 |       resultobj = PyString_FromString(
|      |                 ^
|error: Command '['gcc', ..., '-c', 'scripts/dtc/pylibfdt/libfdt_wrap.c', '-o', 'build/temp.linux-x86_64-cpython-314/scripts/dtc/pylibfdt/libfdt_wrap.o']' returned non-zero exit status 1.
|make[3]: *** [.../scripts/dtc/pylibfdt/Makefile:33: rebuild] Error 1
|make[2]: *** [.../scripts/Makefile.build:497: scripts/dtc/pylibfdt] Error 2
|make[1]: *** [.../Makefile:2403: scripts_dtc] Error 2
|make: *** [Makefile:189: __sub-make] Error 2
|ERROR: oe_runmake failed

[1]: https://git.openembedded.org/openembedded-core/commit/?id=299a82a9c909b73a9b93877d6c1b381ec8f83b04

Signed-off-by: Trevor Gamblin <tgamblin@baylibre.com>