orangepi-rv2-mainline: use mainline U-Boot
- Use mainline U-Boot instead of u-boot-orangepi
  Exception: still using vendor U-Boot SPL
- Booting through NFS as there is not support
  for storage (MMC or USB) yet in the mainline Linux kernel
- Sharing most of the code with BananaPi F3
- docs/orangepi-rv2-mainline.md: instructions
  for building and booting an image

Signed-off-by: Michael Opdenacker <michael.opdenacker@rootcommit.com>