lttng-tools: Skip textrel on rv64
Latest version is causing QA errors e.g.

ERROR: lttng-tools-2.13.0-r0 do_package_qa: QA Issue: lttng-tools: ELF binary /usr/lib/lttng/libexec/lttng-consumerd has relocations in .text
lttng-tools: ELF binary /usr/bin/lttng has relocations in .text
lttng-tools: ELF binary /usr/bin/lttng-crash has relocations in .text
lttng-tools: ELF binary /usr/bin/lttng-relayd has relocations in .text
lttng-tools: ELF binary /usr/bin/lttng-sessiond has relocations in .text [textrel]

Signed-off-by: Khem Raj <raj.khem@gmail.com>