linux-k3: add recipe for SpacemiT K3
Backport a patch from upstream to ensure that the build works for newer
GCC versions (e.g. Fedora 44 has 16.1), which is not yet in 6.18:

|tgamblin@megalith ~/workspace/git/linux (master)$ git tag --contains 905c559e51497
|v7.1-rc4
|v7.1-rc5

Without it, we see errors like:

| In file included from /home/tgamblin/workspace/yocto/bitbake-builds/meta-riscv-oe-nodistro-master-k3-bsp/build/tmp/work-shared/k3-pico-itx/kernel-source/scripts/gcc-plugins/randomize_layout_plugin.c:19:
| /home/tgamblin/workspace/yocto/bitbake-builds/meta-riscv-oe-nodistro-master-k3-bsp/build/tmp/work-shared/k3-pico-itx/kernel-source/scripts/gcc-plugins/gcc-common.h: In function 'void debug_tree(const_tree)':
| /home/tgamblin/workspace/yocto/bitbake-builds/meta-riscv-oe-nodistro-master-k3-bsp/build/tmp/work-shared/k3-pico-itx/kernel-source/scripts/gcc-plugins/gcc-common.h:417:20: error: 'CONST_CAST_TREE' was not declared in this scope; did you mean 'CONST_CAST_EXPR'?
|   417 |         debug_tree(CONST_CAST_TREE(t));
|       |                    ^~~~~~~~~~~~~~~
|       |                    CONST_CAST_EXPR
| /home/tgamblin/workspace/yocto/bitbake-builds/meta-riscv-oe-nodistro-master-k3-bsp/build/tmp/work-shared/k3-pico-itx/kernel-source/scripts/gcc-plugins/gcc-common.h: In function 'void debug_gimple_stmt(const_gimple_ptr)':
| /home/tgamblin/workspace/yocto/bitbake-builds/meta-riscv-oe-nodistro-master-k3-bsp/build/tmp/work-shared/k3-pico-itx/kernel-source/scripts/gcc-plugins/gcc-common.h:312:47: error: expected primary-expression before ',' token
|   312 | #define CONST_CAST_GIMPLE(X) CONST_CAST(gimple, (X))
|       |                                               ^
| /home/tgamblin/workspace/yocto/bitbake-builds/meta-riscv-oe-nodistro-master-k3-bsp/build/tmp/work-shared/k3-pico-itx/kernel-source/scripts/gcc-plugins/gcc-common.h:422:27: note: in expansion of macro 'CONST_CAST_GIMPLE'
|   422 |         debug_gimple_stmt(CONST_CAST_GIMPLE(s));
|       |                           ^~~~~~~~~~~~~~~~~
| /home/tgamblin/workspace/yocto/bitbake-builds/meta-riscv-oe-nodistro-master-k3-bsp/build/tmp/work-shared/k3-pico-itx/kernel-source/scripts/gcc-plugins/gcc-common.h:312:30: error: 'CONST_CAST' was not declared in this scope; did you mean 'CONST_INT'?
|   312 | #define CONST_CAST_GIMPLE(X) CONST_CAST(gimple, (X))
|       |                              ^~~~~~~~~~
| /home/tgamblin/workspace/yocto/bitbake-builds/meta-riscv-oe-nodistro-master-k3-bsp/build/tmp/work-shared/k3-pico-itx/kernel-source/scripts/gcc-plugins/gcc-common.h:422:27: note: in expansion of macro 'CONST_CAST_GIMPLE'
|   422 |         debug_gimple_stmt(CONST_CAST_GIMPLE(s));
|       |                           ^~~~~~~~~~~~~~~~~
| make[3]: *** [/home/tgamblin/workspace/yocto/bitbake-builds/meta-riscv-oe-nodistro-master-k3-bsp/build/tmp/work-shared/k3-pico-itx/kernel-source/scripts/gcc-plugins/Makefile:54: scripts/gcc-plugins/randomize_lay
out_plugin.so] Error 1
| make[2]: *** [/home/tgamblin/workspace/yocto/bitbake-builds/meta-riscv-oe-nodistro-master-k3-bsp/build/tmp/work-shared/k3-pico-itx/kernel-source/scripts/Makefile.build:556: scripts/gcc-plugins] Error 2
| make[1]: *** [/home/tgamblin/workspace/yocto/bitbake-builds/meta-riscv-oe-nodistro-master-k3-bsp/build/tmp/work-shared/k3-pico-itx/kernel-source/Makefile:1263: scripts] Error 2
| make: *** [/home/tgamblin/workspace/yocto/bitbake-builds/meta-riscv-oe-nodistro-master-k3-bsp/build/tmp/work-shared/k3-pico-itx/kernel-source/Makefile:248: __sub-make] Error 2
| ERROR: oe_runmake failed

Co-developed-by: Trevor Gamblin <tgamblin@baylibre.com>
Signed-off-by: Trevor Gamblin <tgamblin@baylibre.com>
Signed-off-by: Yingjie Liu <yingjie-liu@spacemit.com>